# Generated by Django 3.1.3 on 2020-11-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follwers',
            new_name='followers',
        ),
    ]
